export const tokenList = {
  So11111111111111111111111111111111111111112: {
    mint: "So11111111111111111111111111111111111111112",
    decimals: 9,
    freezeAuthority: null,
    mintAuthority: null,
    tokenType: "Legacy",
    tokenList: {
      name: "Wrapped SOL",
      symbol: "SOL",
      image:
        "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png",
      extensions: {
        coingeckoId: "wrapped-solana",
      },
      chainId: 101,
    },
    tokenMetadata: {
      onChainInfo: {
        name: "Wrapped SOL",
        symbol: "SOL",
        metadata: "6dM4TqWyWJsbx7obrdLcviBkTafD5E8av61zfU6jq57X",
        updateAuthority: "AqH29mZfQFgRpfwaPoTMWSKJ5kqauoc1FwVBRksZyQrt",
        isMasterEdition: null,
        edition: null,
        uri: "",
        sellerFeeBasisPoints: 0,
        primarySaleHappened: false,
        isMutable: true,
        creators: [],
        ruleSet: null,
        collection: null,
        collectionDetails: null,
        uses: null,
      },
      offChainInfo: null,
    },
  },
  EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v: {
    mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    decimals: 6,
    freezeAuthority: "3sNBr7kMccME5D55xNgsmYpZnzPgP2g12CixAajXypn6",
    mintAuthority: "2wmVCSfPxGPjrnMMn7rchp4uaeoTqN39mXFC2zhPdri9",
    tokenType: "Legacy",
    tokenList: {
      name: "USD Coin",
      symbol: "USDC",
      image:
        "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/logo.png",
      extensions: {
        coingeckoId: "usd-coin",
      },
      chainId: 101,
    },
    tokenMetadata: {
      onChainInfo: {
        name: "USD Coin",
        symbol: "USDC",
        metadata: "5x38Kp4hvdomTCnCrAny4UtMUt5rQBdB6px2K1Ui45Wq",
        updateAuthority: "2wmVCSfPxGPjrnMMn7rchp4uaeoTqN39mXFC2zhPdri9",
        isMasterEdition: null,
        edition: null,
        uri: "",
        sellerFeeBasisPoints: 0,
        primarySaleHappened: false,
        isMutable: true,
        creators: [],
        ruleSet: null,
        collection: null,
        collectionDetails: null,
        uses: null,
      },
      offChainInfo: null,
    },
  },
  "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R": {
    mint: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    decimals: 6,
    freezeAuthority: null,
    mintAuthority: null,
    tokenType: "Legacy",
    tokenList: {
      name: "Raydium",
      symbol: "RAY",
      image:
        "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R/logo.png",
      extensions: {
        coingeckoId: "raydium",
      },
      chainId: 101,
    },
    tokenMetadata: {
      onChainInfo: {
        name: "Raydium",
        symbol: "RAY",
        metadata: "GMrwFHibMxDtx4aPznekZ7RoJLZGzzLGRSWeNTf3XV2",
        updateAuthority: "7nJGERf1LZpjn4uTfcDZLJ6YRtvdSExAB9uK851zT6do",
        isMasterEdition: null,
        edition: null,
        uri: "",
        sellerFeeBasisPoints: 0,
        primarySaleHappened: false,
        isMutable: true,
        creators: [],
        ruleSet: null,
        collection: null,
        collectionDetails: null,
        uses: null,
      },
      offChainInfo: null,
    },
  },
  Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1: {
    mint: "Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1",
    decimals: 6,
    freezeAuthority: null,
    mintAuthority: "GyktbGXbH9kvxP8RGfWsnFtuRgC7QCQo2WBqpo3ryk7L",
    tokenType: "Legacy",
    tokenList: {
      name: "Saber Protocol Token",
      symbol: "SBR",
      image:
        "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1/logo.svg",
      extensions: {
        coingeckoId: "saber",
      },
      chainId: 101,
    },
    tokenMetadata: {
      onChainInfo: {
        name: "Saber Protocol Token",
        symbol: "SBR",
        metadata: "EtpLDkv7ZDL5LTEqrEPzbjdq5tvnkkdU2hECx3qJqsJG",
        updateAuthority: "GyktbGXbH9kvxP8RGfWsnFtuRgC7QCQo2WBqpo3ryk7L",
        isMasterEdition: null,
        edition: null,
        uri: "",
        sellerFeeBasisPoints: 0,
        primarySaleHappened: false,
        isMutable: true,
        creators: [],
        ruleSet: null,
        collection: null,
        collectionDetails: null,
        uses: null,
      },
      offChainInfo: null,
    },
  },
  Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB: {
    mint: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    decimals: 6,
    freezeAuthority: "Q6XprfkF8RQQKoQVG33xT88H7wi8Uk1B1CC7YAs69Gi",
    mintAuthority: "Q6XprfkF8RQQKoQVG33xT88H7wi8Uk1B1CC7YAs69Gi",
    tokenType: "Legacy",
    tokenList: {
      name: "USDT",
      symbol: "USDT",
      image:
        "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB/logo.svg",
      extensions: {
        coingeckoId: "tether",
      },
      chainId: 101,
    },
    tokenMetadata: {
      onChainInfo: {
        name: "USDT",
        symbol: "USDT",
        metadata: "8c3zk1t1qt3RU43ckuvPkCS7HLbjJqq3J3Me8ov4aHrp",
        updateAuthority: "Q6XprfkF8RQQKoQVG33xT88H7wi8Uk1B1CC7YAs69Gi",
        isMasterEdition: null,
        edition: null,
        uri: "",
        sellerFeeBasisPoints: 0,
        primarySaleHappened: false,
        isMutable: true,
        creators: [],
        ruleSet: null,
        collection: null,
        collectionDetails: null,
        uses: null,
      },
      offChainInfo: null,
    },
  },
  "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E": {
    mint: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
    decimals: 6,
    freezeAuthority: null,
    mintAuthority: "6krMGWgeqD4CySfMr94WcfcVbf2TrMzfshAk5DcZ7mbu",
    tokenType: "Legacy",
    tokenList: {
      name: "Wrapped Bitcoin (Sollet)",
      symbol: "soBTC",
      image:
        "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E/logo.png",
      extensions: {
        coingeckoId: "wrapped-bitcoin-sollet",
      },
      chainId: 101,
    },
    tokenMetadata: {
      onChainInfo: {
        name: "Wrapped Bitcoin (Sollet)",
        symbol: "BTC",
        metadata: "F4zNPXoqasVow544cKMQTPaVW4kmxaJXiN9PG9vqcjDt",
        updateAuthority: "6krMGWgeqD4CySfMr94WcfcVbf2TrMzfshAk5DcZ7mbu",
        isMasterEdition: null,
        edition: null,
        uri: "",
        sellerFeeBasisPoints: 0,
        primarySaleHappened: false,
        isMutable: true,
        creators: [],
        ruleSet: null,
        collection: null,
        collectionDetails: null,
        uses: null,
      },
      offChainInfo: null,
    },
  },
  orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE: {
    mint: "orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE",
    decimals: 6,
    freezeAuthority: null,
    mintAuthority: "23zF9Azpe9CN4iPeTsQndD1mQpcb5Gz1qFREL5gPTZvG",
    tokenType: "Legacy",
    tokenList: {
      name: "Orca",
      symbol: "ORCA",
      image:
        "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE/logo.png",
      extensions: {
        coingeckoId: "orca",
      },
      chainId: 101,
    },
    tokenMetadata: {
      onChainInfo: {
        name: "Orca",
        symbol: "ORCA",
        metadata: "H98wvVNwFmCkRtyEz9EgkQfWwYXZHsVq21o7eSWagWca",
        updateAuthority: "8DzsCSvbvBDYxGB4ytNF698zi6Dyo9dUBVRNjZQFHSUt",
        isMasterEdition: null,
        edition: null,
        uri: "",
        sellerFeeBasisPoints: 0,
        primarySaleHappened: false,
        isMutable: true,
        creators: [],
        ruleSet: null,
        collection: null,
        collectionDetails: null,
        uses: null,
      },
      offChainInfo: null,
    },
  },
  SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt: {
    mint: "SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt",
    decimals: 6,
    freezeAuthority: null,
    mintAuthority: null,
    tokenType: "Legacy",
    tokenList: {
      name: "Serum",
      symbol: "SRM",
      image:
        "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt/logo.png",
      extensions: {
        coingeckoId: "serum",
      },
      chainId: 101,
    },
    tokenMetadata: {
      onChainInfo: {
        name: "Serum",
        symbol: "SRM",
        metadata: "3fQrTMddHhvJrGgV1H4uWZcJG1UzWzYPn8dKp6TdqKbo",
        updateAuthority: "AqH29mZfQFgRpfwaPoTMWSKJ5kqauoc1FwVBRksZyQrt",
        isMasterEdition: null,
        edition: null,
        uri: "",
        sellerFeeBasisPoints: 0,
        primarySaleHappened: false,
        isMutable: true,
        creators: [],
        ruleSet: null,
        collection: null,
        collectionDetails: null,
        uses: null,
      },
      offChainInfo: null,
    },
  },
};
